name: Zip Files

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: data/
          dest: data.zip
