name: Zip Files

on:
  workflow_dispatch:
  push:
    paths:
      - data/**

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1.2
        with:
          files: data/
          dest: data.zip
      - uses: EndBug/add-and-commit@v7
        with:
          add: '["data.zip"]'
          message: 'Update data archive'
          push: true
